/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_client_taliscocaa;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jason Nathaniel
 */
public class Daftar_Acara extends javax.swing.JFrame {

    public Daftar_Acara() {
        initComponents();
        refreshTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelDaftarAcara = new javax.swing.JLabel();
        btnReservasi = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDaftarAcara = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        spinnerQtty = new javax.swing.JSpinner();
        btnMenu = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        labelDaftarAcara.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        labelDaftarAcara.setForeground(new java.awt.Color(255, 255, 255));
        labelDaftarAcara.setText("DAFTAR ACARA");
        getContentPane().add(labelDaftarAcara);
        labelDaftarAcara.setBounds(300, 10, 300, 47);

        btnReservasi.setBackground(new java.awt.Color(204, 204, 204));
        btnReservasi.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReservasi.setForeground(new java.awt.Color(51, 51, 51));
        btnReservasi.setText("Reservasi");
        btnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservasiActionPerformed(evt);
            }
        });
        getContentPane().add(btnReservasi);
        btnReservasi.setBounds(740, 400, 120, 32);

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 204));

        tableDaftarAcara.setBackground(new java.awt.Color(204, 204, 204));
        tableDaftarAcara.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama_acara", "deskripsi", "tanggal_acara", "lokasi_acara", "kapasitas", "harga", "status_acara"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableDaftarAcara);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 70, 760, 310);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("quantity");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 390, 80, 25);

        spinnerQtty.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spinnerQtty);
        spinnerQtty.setBounds(140, 390, 79, 22);

        btnMenu.setBackground(new java.awt.Color(204, 204, 204));
        btnMenu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(51, 51, 51));
        btnMenu.setText("BACK TO MENU");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(680, 440, 180, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/ACARA.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 900, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservasiActionPerformed
        int selectedRow = tableDaftarAcara.getSelectedRow();
        
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih acara yang ingin diklaim terlebih dahulu.");
            return;
        }
        
        String acaraIdStr = tableDaftarAcara.getValueAt(selectedRow, 0).toString(); 
        int acaraId = Integer.parseInt(acaraIdStr); 
        String statusAcara = (String) tableDaftarAcara.getValueAt(selectedRow, 7);
        String kapasitas = tableDaftarAcara.getValueAt(selectedRow, 5).toString();
        int kapasitasInt = Integer.parseInt(kapasitas);
        
        if (!statusAcara.equals("Active")) {
            JOptionPane.showMessageDialog(this, "Acara tidak bisa diklaim. Status acara: " + statusAcara);
            return;
        }
        
        Menu form = new Menu();
        int user_id = form.user_id;
        
        int bookingAmount = (int) spinnerQtty.getValue();
        try {
            
            if(bookingAmount > kapasitasInt){
                JOptionPane.showMessageDialog(this, "Kapasitas tidak memenuhi");
            }
            else{
                insertDataReservasiAcara(bookingAmount, user_id, acaraId);
                
                if (kapasitasInt - bookingAmount > 0) {
                    updateDataAcara("Active", kapasitasInt - bookingAmount, acaraId);
                } else {
                    updateDataAcara("Not Active", kapasitasInt - bookingAmount, acaraId);
                }
                
                updateDataAcara(statusAcara, kapasitasInt, acaraId);
                JOptionPane.showMessageDialog(this, "Acara berhasil diklaim.");
                refreshTable(); 
            }   

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat mengklaim acara.");
        }
    }//GEN-LAST:event_btnReservasiActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        Menu form = new Menu();
        form.show();
    }//GEN-LAST:event_btnMenuActionPerformed
    
    public void refreshTable() {
        DefaultTableModel tableModel = (DefaultTableModel) tableDaftarAcara.getModel();
        tableModel.setRowCount(0);  // Menghapus baris yang ada

        List<String> dataList = viewListDataAcara();
        for (String data : dataList) {
            String[] splitData = data.split("%");
            tableModel.addRow(splitData);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Daftar_Acara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Daftar_Acara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Daftar_Acara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Daftar_Acara.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Daftar_Acara().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReservasi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDaftarAcara;
    private javax.swing.JSpinner spinnerQtty;
    private javax.swing.JTable tableDaftarAcara;
    // End of variables declaration//GEN-END:variables

    private static java.util.List<java.lang.String> viewListDataAcara() {
        project_client_taliscocaa.ProjectWebservice_Service service = new project_client_taliscocaa.ProjectWebservice_Service();
        project_client_taliscocaa.ProjectWebservice port = service.getProjectWebservicePort();
        return port.viewListDataAcara();
    }

    private static void insertDataReservasiAcara(int jumlahTiket, int userId, int acaraId) {
        project_client_taliscocaa.ProjectWebservice_Service service = new project_client_taliscocaa.ProjectWebservice_Service();
        project_client_taliscocaa.ProjectWebservice port = service.getProjectWebservicePort();
        port.insertDataReservasiAcara(jumlahTiket, userId, acaraId);
    }

    private static void updateDataAcara(java.lang.String statusAcara, int kapasitas, int acaraId) {
        project_client_taliscocaa.ProjectWebservice_Service service = new project_client_taliscocaa.ProjectWebservice_Service();
        project_client_taliscocaa.ProjectWebservice port = service.getProjectWebservicePort();
        port.updateDataAcara(statusAcara, kapasitas, acaraId);
    }

}
